services:
  api:
      build: .
      image: app
      ports:
        - "8000:8000"
      volumes:
        - .:/app:ro
  pg:
    image: postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      PGDATA: /PostgreSQL/17/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/PostgreSQL/17/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  pgdata:
